# Site settings
baseurl = "https://primal-iceland.zkynet.cloud/"
languageCode = "en-us"
title = "Primal Iceland"
theme = ""


[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Primal Iceland"
  description = "Your description"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation
  [params.navigation]
    brand = "Primal Iceland"
    # Optional logo as brand stored in img/
    #logo = "logo.svg"
    movement = "Hreyfing"
    handstand = "Handstöður"
    vimhoff = "Öndun"
    #about = "Um Okkur"
    team = "Teymið"
    contact = "Hafa Samband"
