# Site settings
baseurl = "https://primal.zveinn.dev/"
languageCode = "en-us"
title = "Primal Iceland"
theme = ""
disableKinds = ["taxonomy","taxonomyTerm","sitemap","RSS"]

[params]
  name = "Primal Iceland"
  description = "Your description"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Vid fundum ekki siðuna, endilega farið aftur á forsíðu!"
    text = "Please visit [this page](/)"

  # Navigation
  [params.navigation]
    brand = "Primal Iceland"
    # Optional logo as brand stored in img/
    #logo = "logo.png"
    movement = "Movement"
    handstand = "Handstöður"
    annad = "Önnur Námskeið"
    media = "Fjölmiðlar"
    wimhof = "Wim Hof"
    team = "Teymið"
    einkatimar = "Einkatímar"
    contact = "Hafa Samband"
    streita = "Sigrum Streituna"
    empower = "Empower"
    mommur = "Mömmu Þrek"

    # Tracking
  [params.tracking]
    facebook = false
    google = false

