# Site settings
baseurl = "https://primal-iceland.zkynet.cloud/"
languageCode = "en-us"
title = "Primal Iceland"
theme = ""


[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Primal Iceland"
  description = "Your description"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation
  [params.navigation]
    brand = "Primal Iceland"
    # Optional logo as brand stored in img/
    #logo = "logo.svg"
    movement = "Hreyfing"
    handstand = "Handstöður"
    vimhoff = "Öndun"
    about = "Um Okkur"
    team = "Teymið"
    contact = "Hafa Samband"


  





  # basics section
  [params.basics]
    enable = true
    title = "Hvað er við að gera ?"
    subtitle = "Lorem ipsum dolor siLorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.t amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

    [[params.basics.row]]

    [[params.basics.row.list]]
      icon = "fa-heartbeat"
      title = "Vim Hoff"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"


    [[params.basics.row.list]]
      icon = "fa-street-view"
      title = "Leiðleiki og Handstöður"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"
 

    [[params.basics.row.list]]
      icon = "fa-street-view"
      title = "Movement Improvement"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"
 








    # About section
  [params.about]
    enable = true
    title = "Um Okkur"
    subtitle = "Primal Iceland er ný líkamsræktarstöð í glæsilegu húsnæði að Faxafeni 12. Þar er boðið upp á Movement Improvement og Wim Hof námskeið sem og einkatíma, þar sem bæði er unnið í að útrýma verkjum og með æfingamarkmið viðkomandi. Liðleiki og hreyfigeta eru í hávegum höfð.Þrír reynslumiklir þjálfarar reka Primal Iceland, þeir Einar Carl, Helgi Freyr og Þór Guðnason. Þeir smíðuðu húsnæðið sjálfir frá grunni og sérsniðu það eftir sínum þörfum. Þeir endurnýttu mikið, meðal annars við úr pallettum og skápa úr búningsklefa í gömlu herstöðinni. Stöðin verður sú fyrsta sem býður upp á Wim Hof námskeið á Íslandi, enda er Þór eini Íslendingurinn sem hefur lokið kennararéttindum hjá Wim Hof."
    endpoint = "Vertu með okkur!"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      img = "1.jpg"
      date = "2009-2011"
      title = "Our Humble Beginnings"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

    [[params.about.events]]
      img = "2.jpg"
      date = "March 2011"
      title = "An Agency is Born"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

    [[params.about.events]]
      img = "3.jpg"
      date = "December 2012"
      title = "Our Humble Beginnings"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

    [[params.about.events]]
      img = "4.jpg"
      date = "July 2014"
      title = "Phase Two Expansion"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"



  # ÞETTA INFO ER FYRIR MOVEMENT UNDIR SÍÐUNA. MÁ HENDA EF VIÐ NOTUM HANA EKKI.
  [params.movement]
    enable = true
    title = "Movement Improved"
    subtitle = "Skemmtileg námskeið sem blanda saman hinum ýmsu hreyfilistum við leiki og teygjur.<br><br> Við sækjum innblástur frá dansi, bardagalistum, fimleikum og öllu sem að kveikir okkar áhuga og blöndum því saman í skemmtilega og fjölbreytta tíma.Í boði eru bæði byrjendahópar og hefðbundin námskeið. Í hefðbundnu námskeiðunum er gert ráð fyrir að fólk geti fylgt ágætis hraða í æfingunum og sé tilbúið í það að læra á meðan framkvæmt er.<br><br> Í byrjendahópunum er tempóið hægara og æfingar einfaldaðar til þess að sem flestir geti framkvæmt þær.Athugið að námskeiðin, hvorki byrjenda né hefðbundnu hóparnir, eru lausn á stoðkerfisvandamálum. Ef að þau eru til staðar, mælum við alltaf fyrst með einkatíma."

    [[params.movement.row]]

    [[params.movement.row.list]]
      icon = "fa-heartbeat"
      title = "Liðleigi"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"


    [[params.movement.row.list]]
      icon = "fa-free-code-camp"
      title = "Hreyfing"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"

    [[params.movement.row.list]]
      icon = "fa-street-view"
      title = "Annað"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"
 



 # ÞETTA INFO ER FYRIR VIM HOFF UNDIR SÍÐUNA. MÁ HENDA EF VIÐ NOTUM HANA EKKI.
  [params.vimhoff]
    enable = true
    title = "Vim Hoff"
    subtitle = "Lorem ipsum dolor siLorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.t amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

    [[params.vimhoff.row]]

    [[params.vimhoff.row.list]]
      icon = "fa-heartbeat"
      title = "Öndun"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"


    [[params.vimhoff.row.list]]
      icon = "fa-free-code-camp"
      title = "Kulda og Hita þjálfun"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"

    [[params.vimhoff.row.list]]
      icon = "fa-street-view"
      title = "Æfingar og liðleiki"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"
 










  # ÞJÁLFARARNIR !
  [params.team]
    enable = true
    # Possibility to center items
    #center = true
    title = "Eigendur og Þjálfarar Primal Iceland"
    subtitle = "Eithvað um eigendur"
    description = "Meiri og stærri texti um eigendur og þjálfara hjá primal iceland. <br>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde."

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.members]]
      img = "thor.jpg"
      name = "Þór Guðnasson"
      position = "kuldaþjálfun og öndun"
      reportsTo = ""
      livesIn = "[Munich, Germany](#some-maps-url)"
      scope = [
        "UX for [member dashboard](#)",
        "Maintainer for [awesome-project](#)",
        "Open Source [community management](#)"
      ]
      # For bio markdown and even multiline strings are available.
      bio = """Kay is an awesome Lead Designer with heaps of experience in the field of UX.
She worked at Pied Piper for years until they went belly up."""
      social = [
        ["fa-twitter", "#"],
        ["fa-facebook", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.team.members]]
      img = "helgi.jpg"
      name = "Helgi Freyr Rúnarsson"
      position = "Handstöður og liðleiki"
      social = [
        ["fa-twitter", "#"],
        ["fa-facebook", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.team.members]]
      img = "einar.jpg"
      name = "Einar Carl Alexsson"
      position = "Styrkur"
      social = [
        ["fa-twitter", "#"],
        ["fa-facebook", "#"],
        ["fa-linkedin", "#"]
      ]












  # Client section
    [params.clients_list]
      enable = true
      # Possibility to center items
      #center = true
      # Optional client title specifying the involvement
      #title = "Used and trusted by"

      # All the clients' logos are stored under 'static/img/logos'.
      # Replace them with your clients's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      [[params.clients]]
        logo = "envato.jpg"
        link = "#"
      [[params.clients]]
        logo = "envato.jpg"
        link = "#"
      [[params.clients]]
        logo = "envato.jpg"
        link = "#"
      [[params.clients]]
        logo = "envato.jpg"
        link = "#"
      [[params.clients]]
        logo = "envato.jpg"
        link = "#"
      [[params.clients]]
        logo = "designmodo.jpg"
        link = "#"

      [[params.clients]]
        logo = "themeforest.jpg"
        link = "#"

      [[params.clients]]
        logo = "creative-market.jpg"
        link = "#"










  # Contact section
  [params.contact]
    enable = true
    title = "Contact us"
    subtitle  = "Lorem ipsum dolor sit amet consectetur."
    buttonText = "Send message"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "your@email.com"

    # Success and error message overwrite for async contact form
    #thanks = "Thank you for awesomely contacting us."
    #error = "Message could not be send. Please contact us at mail@example.com instead."

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Your Name *"
      warning = "Please enter your name."

    [params.contact.form.email]
      text = "Your Email *"
      warning = "Please enter your email address."

    [params.contact.form.phone]
      text = "Your Phone *"
      warning = "Please enter your phone number."

    [params.contact.form.message]
      text = "Your Message *"
      warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"










  # Footer section
  [params.footer]
    enable = true
    copyright = "Published under the Apache License 2.0."

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "#"
      title = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "#"
      title = "Facebook"

    [[params.footer.social]]
      icon = "fa-linkedin"
      link = "#"
      title = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Privacy Policy"
      link = "#"

    [[params.footer.quicklinks]]
      text = "Terms of Use"
      link = "#"
